services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend_container
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://pallet:pallet@timescaledb:5432/warehouse
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app/ai_model/dataset/test_images:/app/images
    depends_on:
      - timescaledb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/frontend/public
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: ["npm", "start"]

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: pallet
      POSTGRES_PASSWORD: pallet
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"

  inference_worker:
    build:
      context: ./backend/
      dockerfile: app/ai_service/Dockerfile.inference_worker
    container_name: inference
    environment:
      - DATABASE_URL=postgresql+psycopg2://pallet:pallet@timescaledb:5432/warehouse
    volumes:
      - ./backend/app/ai_service/images:/app/images:ro
      - ./backend/app/ai_service/inferenced:/app/images/inferenced
    depends_on:
      - timescaledb
    command: ["python", "app/ai_service/app.py"]
