version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_container
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://pallet:pallet@timescaledb_container:5432/warehouse
    ports:
      - "5000:5000"
    depends_on:
      - timescaledb
      - redis

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb_container
    environment:
      POSTGRES_USER: pallet
      POSTGRES_PASSWORD: pallet
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"