version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_container
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://pallet:pallet@timescaledb:5432/warehouse
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app/ai_model/dataset/test_images:/app/images
    depends_on:
      - timescaledb

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/frontend/public  # Ensure local files are mapped correctly
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: ["npm", "start"]  # Automatically start the frontend dev server

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: pallet
      POSTGRES_PASSWORD: pallet
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
